info:
    description: 'Predict the involved driver genes in macrophage perturbation'
    date: '2025-07-28'
    version: '1.0.2'

trainer:
    job_name: 'macrophages'
    version: 'overlappedgenes' # will be replaced by the version in the data_file
    output_dir: '../results'
    max_epochs: 500
    device: 'cuda'
    train_metrics: ['RelPos', 'label#AUROC']
    test_metrics: 'core'
    bar_metrics: ['RelPos', 'label#AUROC']
    monitor_metric: 'RelPos'
    monitor_mode: 'max'
    debugging: false
    early_stopping: true
    patience: 10
    monitor_ma_window: 5
    learning_rate: 0.001
    mixing_strategy: 'uncertainty'
    cotrain_weight: 1.0
    loss_weights:
        vae: 1.0
        dis: 10.0
        cls: 100.0
    seed: 42 # for model initialization


dataset:
    data_dir: '../datasets/bian'
    adata_file: 
        - '../haag/preprocessed.h5ad'
        - 'preprocessed.h5ad'
    split_file: 
        - '../haag/split_df_nonpc_subsplit.parquet'
        - 'split_df_Monocyte.parquet'
    sample_size: 50
    batch_size: 512
    num_workers: 0
    layer_name: 'X'
    var_subset: 'all'
    cotrain_mode: false
    condition_key: 'perturbation'
    source_cell: 'control'
    sample_neg: true
    resampling_mode: true
    
identifier:
    pe_type: 'none'
    organism: null
    finetune: false
    rec_loss: 'mse'
    dis_loss: 'edist_euclidean'
    cls_loss: 'focal_loss'
    extractor_type: 'attn'


extractor:
    dim_genes: null
    dim_hidden: 512
    num_layers: 2
    dim_latent: 128
    dropout: 0.1
    use_batch_norm: false
    use_layer_norm: true
    act: 'leakyrelu'
    variational: false

fuser:
    strategy: 'bilinear'
    dim_feat: 1
